### ISSUE TITLE
multi host support

### ISSUE THREAD

**Issue by leslie-wang** [gopher-net/ipvlan-docker-plugin#25]
I start 2 nodes, install plugin, and start container with ipvlan plugin, but seems like they have same interface. So does plugin currently only support single host, not multi host?

**Comment by YujiOshima** [comment]
I don't understand this mean > "but seems like they have same interface"
which mode do you use?(l2 or l3)
If you use l2 mode, confirm a subnet of container network correspond to the master interface and the setting of default GW.
Let me know your ip addresses of hosts and containers.

**Comment by mattmcclean** [comment]
I am trying to get multi-host working but not sure how to do this. I followed the steps below:
- Created a docker swarm cluster on EC2 with one swarm master and 2 nodes using Consul as the K/V store using docker-machine. Output is as follows:

> NAME           ACTIVE   DRIVER       STATE     URL                        SWARM                  DOCKER
> consul         -        amazonec2    Running   tcp://52.50.18.54:2376                            v1.10.1
> ipvlan-demo    -        amazonec2    Running   tcp://52.50.42.190:2376    ipvlan-demo (master)   v1.10.1
> ipvlan-demo1   -        amazonec2    Running   tcp://52.49.216.241:2376   ipvlan-demo            v1.10.1
> ipvlan-demo2   -        amazonec2    Running   tcp://52.50.43.60:2376     ipvlan-demo            v1.10.1
- Installed and started the ipvlan network plugin process on each swarm node 
- Ran the docker network create command as follows:

> docker network create -d ipvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o host_iface=eth0 -o mode=l2 net1
- Checked the network config with cmd: `docker network ls` and returned the following:

> NETWORK ID          NAME                  DRIVER
> 6234d41d173c        ipvlan-demo2/bridge   bridge
> ece3f95f35da        ipvlan-demo/bridge    bridge
> 78535c02586f        ipvlan-demo1/net1     ipvlan
> 068e851f4dab        ipvlan-demo1/bridge   bridge
> c64345376881        ipvlan-demo1/host     host
> 488859a35aa1        ipvlan-demo2/host     host
> f87bf44d218d        ipvlan-demo2/none     null
> 095c4b359539        ipvlan-demo/none      null
> ae5c7eada73a        ipvlan-demo/host      host

If you notice the network name `net1`is only created on one node in the cluster. How is it possible to create the network across all nodes? Do I need to run the same command on all of them or does ipvlan not support multi-host networking in L2 mode?

**Comment by nerdalert** [comment]
Hey matt! It was single network originally so one overwrites the other, doh. I updated the macvlan one to multi-net a couple weeks ago but got sidetracked with other projects/work. In the meantime can you check out the PR that has native macvlan/ipvlan in libnetwork natively? https://github.com/docker/libnetwork/ PR 964

There is a binary in the link in the patch notes if you don't want to build engine+libnetwork. Don't hesitate to add feedback or :+1: etc in libnetwork if it works or issues if you have any. Lemme know if its missing anything you need and close this out if thats good for you. Thanks!

**Comment by nerdalert** [comment]
@YujiOshima  with Ipvlan / Macvlan natively in Docker/Libnetwork we should couple go-bgp on there asap! Here is the PR if you want to :+1: if it works for you  https://github.com/docker/libnetwork/ PR 964

**Comment by jacohend** [comment]
@nerdalert I'm not getting ipvlan multihost to work on experimental. Same subnet, docker daemons all using same k/v store and properly display the overlays of other nodes. But ipvlan only appears locally in all cases.
