### ISSUE TITLE
need help for Ipvlan L3 mode !!!

### ISSUE THREAD

**Issue by prateekgogia** [gopher-net/ipvlan-docker-plugin#27]
Hi 

I added this comment originally in #6. I am opening this as a new issue, since, the title for that bug is different. Can someone guide me through this, I am not sure what am I missing. 

I am still seeing this error when trying to use ipvlan in L3 mode. I have added disable default gw setting in docker network create command as well.
docker: Error response from daemon: Cannot start container 2dcb35966fcce550050fbe0e781c7328e94a6cd68953536e68cc1a9c375c253f: [9] System error: failed to set gateway while updating gateway: file exists.

Steps:
## *Step 1 *- Run ipvlan binary:

./ipvlan-docker-plugin-0.2-Linux-x86_64 -d --mode="l3" --ipvlan-subnet="192.169.57/24" --host-interface="enp0s3" --gateway="192.169.57.1"&
## Step 2 - Create Docker network:

docker network create -d ipvlan --subnet=192.169.57.0/24 --gateway=192.169.57.1 -o host_iface=enp0s3 -o mode=l3 -o com.docker.network.driver.disable_default_gateway net1

DEBU[0015] Network Create Called: [ {NetworkID:5a6c6ff0a97e9cf712165a6670445b55995c232e7528e521ae0a2f44f3ebaf48 Options:map[com.docker.network.generic:map[com.docker.network.driver.disable_default_gateway: host_iface:enp0s3 mode:l3]] IpV4Data:[{AddressSpace: Pool:192.169.57.0/24 Gateway:192.169.57.1/24 AuxAddresses:map[]}] ipV6Data:[]} ]
DEBU[0015] Libnetwork Opts Sent: [ com.docker.network.driver.disable_default_gateway ] Value: [ ]
DEBU[0015] Libnetwork Opts Sent: [ host_iface ] Value: [ enp0s3 ]
DEBU[0015] Libnetwork Opts Sent: [ mode ] Value: [ l3 ]
DEBU[0015] Ipvlan mode is L3 [ l3 ]
DEBU[0015] Adding route for the local ipvlan subnet [ 192.169.57.0/24 ] in the default namespace using the specified host interface [ enp0s3]
## Step 3: Start the contaiener, this is where it fails -

docker run --net=net1 -it --rm myubuntu bash DEBU[0019] The container subnet for this context is [ 192.169.57.2/24 ]
INFO[0019] Allocated container IP: [ 192.169.57.2/24 ]
DEBU[0019] Create endpoint response: &{Interface:{Address: AddressIPv6: MacAddress:7a:42:00:00:00:00}}
DEBU[0019] Create endpoint 1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5 &{Interface:{Address: AddressIPv6: MacAddress:7a:42:00:00:00:00}}
DEBU[0019] Join request: &{NetworkID:5a6c6ff0a97e9cf712165a6670445b55995c232e7528e521ae0a2f44f3ebaf48 EndpointID:1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5 SandboxKey:/var/run/docker/netns/0add445bda28 Options:map[]}
INFO[0019] Created ipvlan link: [ 1410c ] with a mode: [ l3 ]
DEBU[0019] Join response: &{Gateway: InterfaceName:{SrcName:1410c DstName: DstPrefix:eth} StaticRoutes:[0xc8201ab830] DisableGatewayService:false}
DEBU[0019] Join endpoint 5a6c6ff0a97e9cf712165a6670445b55995c232e7528e521ae0a2f44f3ebaf48:1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5 to /var/run/docker/netns/0add445bda28
DEBU[0020] Leave request: &{NetworkID:5a6c6ff0a97e9cf712165a6670445b55995c232e7528e521ae0a2f44f3ebaf48 EndpointID:1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5 Options:map[]}
DEBU[0020] Leave 5a6c6ff0a97e9cf712165a6670445b55995c232e7528e521ae0a2f44f3ebaf48:1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5
DEBU[0020] Delete endpoint request: &{NetworkID:5a6c6ff0a97e9cf712165a6670445b55995c232e7528e521ae0a2f44f3ebaf48 EndpointID:1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5}
DEBU[0020] Delete endpoint 1410ccd52f0b32401bebf404caedb68a3753613d302d917d48886f9b624f6cb5
DEBU[0020] The requested interface to delete [ 1410c ] was not found on the host: route ip+net: no such network interface
ERRO[0020] The requested interface to delete [ 1410c ] was not found on the host.
docker: Error response from daemon: Cannot start container 2dcb35966fcce550050fbe0e781c7328e94a6cd68953536e68cc1a9c375c253f: [9] System error: failed to set gateway while updating gateway: file exists.

Thanks

**Comment by nerdalert** [comment]
Hey @prateekgogia ! Sorry for the delay. Been working on a PR to get Ipvlan into libnetwork. I pushed the PR today so if you can give it a couple of days we should have it natively in Docker. Close out the issue if that cool with you. I will clean this up so it can be an example for folks hacking on 3rd party plugins but getting native ipvlan/macvlan in docker and polished up will be the focus the next couple weeks. Take a look and give it a test. Binary is in the commit link. https://github.com/docker/libnetwork/ pull request 964

**Comment by prateekgogia** [comment]
@nerdalert Thanks for the reply. Will try it out.

**Comment by nerdalert** [comment]
He @prateekgogia wanted to update with these notes. If you test it out and have any issues or use cases it doesn't solve don't hesitate to ping. [Macvlan, Ipvlan and 802.1q Trunk Driver Notes](https://gist.github.com/nerdalert/c0363c15d20986633fda#getting-started) 
Thanks!
