### ISSUE TITLE
unable to build 

### ISSUE THREAD

**Issue by shmurthy62** [gopher-net/ipvlan-docker-plugin#5]
I am seeing the following error when I build -

../../../docker/libnetwork/iptables/firewalld.go:75: cannot use c.sysconn.Object(dbusInterface, dbus.ObjectPath(dbusPath)) (type dbus.BusObject) as type *dbus.Object in assignment: need type assertion

what do I need to do to get this resolved.

**Comment by orivej** [comment]
You need a stable godbus that you can probably get with

``` sh
cd $GOPATH/src/github.com/godbus/dbus
git checkout v2
```

**Comment by nerdalert** [comment]
Added Godep for dependency management. Readme updated with instructions.
